#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  datasource:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/internet_hospital_regulation?zeroDateTimeBehavior=convertToNull&useSSL=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
    driverClassName: net.sf.log4jdbc.DriverSpy
    username: root
    password: 123456